export PATH=$HOME/bin:$HOME/.local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
# Use powerline
USE_POWERLINE="true"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
    source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
    source /usr/share/zsh/manjaro-zsh-prompt
fi

FASTFETCH=`which fastfetch 2> /dev/null`
if [ $? -eq 0 ]; then
    ${FASTFETCH}
fi

plugins=(git git-extras zsh-autosuggestions zsh-syntax-highlighting tmux history extract colorize docker z)

source $ZSH/oh-my-zsh.sh
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Predictable SSH authentication socket location.
SOCK="${HOME}/.ssh-agent-tmux"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]
then
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi

#export EDITOR='vim'
export CMAKE_DEB="-DCMAKE_EXPORT_COMPILE_COMMANDS=Yes -DCMAKE_BUILD_TYPE=Debug"

alias ls='exa --color=always --icons=always --group-directories-first --git'
alias l='exa -lah --color=always --icons=always --group-directories-first --git'
alias la='exa -la --color=always --icons=always --group-directories-first --git'
alias ll='exa -l --color=always --icons=always --group-directories-first --git'
alias lt='exa -aT --color=always --icons=always --group-directories-first --git'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
