---
- hosts: localhost
  connection: local
  tasks:
  - name: Install ecdev packages
    become: yes
    apt:
      pkg:
      - build-essential
      - net-tools
      - doxygen
      - graphviz
      - autoconf
      - libtool
      - cmake
      - pkg-config
      state: latest
      update_cache: yes
