---
- name: Clone zsh-syntax-highlighting-repo to oh my zsh dir
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ${HOME}/.oh-my-zsh/plugins/zsh-syntax-highlighting
  tags:
    - zsh-syntax-highlighting
    - devel
