---
- name: Install emacs
  package:
    name: emacs-nox
    state: present
  become: yes
  tags:
  - emacs
  - devel
  - editors

- name: Install Emacs Config
  git:
    repo: https://github.com/ntc490/emacs.d
    dest: ${HOME}/.emacs.d
    recursive: yes
  ignore_errors: yes
  tags:
  - emacs
  - devel
  - editors
