---
- name: Install screen
  package:
    name: screen
    state: present
  become: yes
  tags:
  - screen
  - devel

- name: Symlink screen config
  file:
    src: "{{ role_path }}/files/screenrc"
    dest: ${HOME}/.screenrc
    state: link
    force: yes
  tags:
  - dotfiles
  - screen
  - devel
